# Generated by Django 3.1.5 on 2021-03-05 22:04

from django.db import migrations, models
import vditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("content", vditor.fields.VditorTextField()),
            ],
        ),
        migrations.CreateModel(
            name="VditorTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("content", vditor.fields.VditorTextField()),
            ],
        ),
    ]
