# Generated by Django 3.1.5 on 2021-02-07 03:41

from django.db import migrations, models
import vditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vditor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VditorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', vditor.fields.VditorTextField()),
            ],
        ),
    ]
