name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  claude-code:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: anthropics/claude-code-action@beta
        with:
          trigger_phrase: '@claude'
          timeout_minutes: '60'
          anthropic_api_key: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_tools: |
            Bash
            Read
            Write
            Edit
            MultiEdit
            Glob
            Grep
            LS
            WebFetch
            WebSearch
            GitHubRead
            GitHubReview
            Task
          claude_env: |
            ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}