name: Mirror GitHub Auto Queried Repos to Gitee

on:
  push:
    branches: main

jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/pi-dal
        dst: gitee/pi-dal
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        debug: true
        white_list: django-vditor