name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["5.2"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: true

    - name: Install dependencies
      run: |
        pdm install --dev
        pdm add django==${{ matrix.django-version }}

    - name: Run Linting (flake8)
      run: pdm run lint

    - name: Run Formatting Check (black)
      run: pdm run format-check

    - name: Run Type Checking (mypy)
      run: pdm run typecheck

    - name: Run Unit Tests with Coverage
      run: |
        pdm run coverage
        pdm run coverage-report
        pdm run coverage-xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.11'
        cache: true
    
    - name: Install dependencies
      run: pdm install --dev
    
    - name: Run security scan
      run: pdm run safety check --json || true